#!/bin/sh

set -e

die() {
    echo "$@" >&2
    exit 1
}

if [ `id -u` != 0 ]; then
    die "Please run as root"
fi

SM="$(dmidecode -s system-manufacturer)"
SPN="$(dmidecode -s system-product-name)"
BPN="$(dmidecode -s baseboard-product-name)"

# try System Information > Manufacturer first
case "$SM" in
  "Joytech")
    case "$SPN" in
      "Wedge-AC-F 20-001329")
        manufacturer=accton
      ;;
      *)
        die "Unknown system product name; please report SM=$SM, SPN=$SPN, BPN=$BPN"
      ;;
    esac
  ;;
  "Mellanox Technologies Ltd.")
    manufacturer=mellanox
  ;;
  "To be filled by O.E.M.")
    case "$BPN" in
      "PCOM-B632VG-ECC-FB-ACCTON-D")
        manufacturer=accton
      ;;
      *)
        die "Unknown board product name; please report SM=$SM, SPN=$SPN, BPN=$BPN"
      ;;
    esac
  ;;
  *)
    die "Unknown manufacturer; please report SM=$SM, SPN=$SPN, BPN=$BPN"
  ;;
esac

# next look at System Information > Product Name
case "$manufacturer-$SPN" in
  "mellanox-\"MSN2100-CB2FO\"")
    model=sn2100
  ;;
  "accton-Wedge-AC-F 20-001329")
    model=wedge40
  ;;
  "accton-To be filled by O.E.M.")
    case "$BPN" in
      "PCOM-B632VG-ECC-FB-ACCTON-D")
        model=wedge100
      ;;
      *)
        die "Unknown board product name; please report SM=$SM, SPN=$SPN, BPN=$BPN"
      ;;
    esac
  ;;
  *)
    die "Unknown system product name; please report SM=$SM, SPN=$SPN, BPN=$BPN"
  ;;
esac

cat <<EOF
manufacturer=$manufacturer
model=$model
EOF

