#!/bin/sh

# starts syncd; also needs to start these other daemons:
# https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-orchagent/start.sh
# also should run swssconfig

set -e -x

. "$SNAP/lib/functions.sh"

setup_env

# bail successfully when unconfigured to allow snap install
if [ "$SONIC_HWSKU" = unconfigured ]; then
    exit 0
fi

detect_hwsku
detect_mac_address

# create work dir in writable area; required by SAI at least for the broadcom
# backend
SONIC_SWSS_RUN="$SNAP_DATA/run/swss"
mkdir -p "$SONIC_SWSS_RUN"
cd "$SONIC_SWSS_RUN"

# see https://github.com/Azure/SONiC/issues/51
ln -sf "$SNAP_DATA/run/redis.sock" link-to-redis-socket.sock

# FIXME this shouldn't be in a common file
if [ "$SONIC_BACKEND" = broadcom ]; then
    ln -sfn "$SNAP/$SONIC_BACKEND/etc/bcm" bcm-configs
fi

SONIC_SYNC_PROFILE="$SNAP/$SONIC_BACKEND/etc/syncd.d/$SONIC_HWSKU.profile"

if [ -n "$SONIC_SYNC_PROFILE_OVERRIDE" ]; then
    SONIC_SYNC_PROFILE="$SONIC_SYNC_PROFILE_OVERRIDE"
fi

syncd -N -p "$SONIC_SYNC_PROFILE" &

# wait for syncd to be ready
while [ $("$SNAP/command-redis-cli.wrapper" -n 1 HLEN HIDDEN) = 0 ]; do
    sleep 1
done

orchagent -m "$SONIC_MAC_ADDRESS" &
# need to find hwsku specific port_config.ini
#portsyncd -p port_config.ini  &
intfsyncd &
neighsyncd &

# need to list extra SWSS configs per hwsku
#for file in $SNAP/etc/swss/config.d/*; do
#    swssconfig "$file"
#    sleep 1
#done

