#!/bin/sh

# starts syncd; also needs to start these other daemons:
# https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-orchagent/start.sh
# also should run swssconfig

set -e -x

. "$SNAP/lib/functions.sh"

setup_env

# create work dir in writable area; required by SAI at least for the broadcom backend
SONIC_SWSS_RUN="$SNAP_DATA/run/swss"
mkdir -p "$SONIC_SWSS_RUN"
cd "$SONIC_SWSS_RUN"

# see https://github.com/Azure/SONiC/issues/51
ln -sf "$SNAP_DATA/run/redis.sock" link-to-redis-socket.sock

# FIXME this shouldn't be in a common file
if [ "$SONIC_BACKEND" = broadcom ]; then
    ln -sfn "$SNAP/$SONIC_BACKEND/etc/bcm" bcm-configs
fi

SONIC_SYNC_PROFILE="$SNAP/$SONIC_BACKEND/etc/syncd.d/$SONIC_HWSKU.profile"

if [ -n "$SONIC_SYNC_PROFILE_OVERRIDE" ]; then
    SONIC_SYNC_PROFILE="$SONIC_SYNC_PROFILE_OVERRIDE"
fi

exec "$SNAP/$SONIC_BACKEND/usr/bin/syncd" \
    -N \
    -p "$SONIC_SYNC_PROFILE" \
    "$@"
