#!/bin/sh

# starts syncd; also needs to start these other daemons:
# https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-orchagent/start.sh

set -e -x

. "$SNAP/lib/functions.sh"

setup_env

# this is required for link-to-redis-socket.sock to be found
cd "$SNAP"

exec "$SNAP/$SONIC_BACKEND/usr/bin/syncd" -N "$@"
